name: Integration Tests

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test-image:
    uses: parameter1/actions/.github/workflows/website-build-push-test.yml@main
    strategy:
      matrix:
        ###############################################
        #v# Make sure this matches the site matrix! #v#
        ###############################################
        site:
          - { dir: ccnewsnow.com, stack: leonis, id: 60c28bc3d28860bc334ebcb2, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-ccnewsnow.com }
          - { dir: diverseeducation.com, stack: leonis, id: 60c281c6d28860bc33464ae0, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-diverseeducation.com }
          - { dir: diversemilitary.net, stack: leonis, id: 60c28c0dd28860bc334ed723, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-diversemilitary.net }
          - { dir: divhealth.net, stack: leonis, id: 60c28c4bd28860bc334f485d, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-divhealth.net }
          - { dir: ccnewsnow.com, stack: virgon, id: 60c28bc3d28860bc334ebcb2, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-ccnewsnow.com }
          - { dir: diverseeducation.com, stack: virgon, id: 60c281c6d28860bc33464ae0, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-diverseeducation.com }
          - { dir: diversemilitary.net, stack: virgon, id: 60c28c0dd28860bc334ed723, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-diversemilitary.net }
          - { dir: divhealth.net, stack: virgon, id: 60c28c4bd28860bc334f485d, account: diverse, tenant: diverse_all, rancher_label: cox-matthews-associates-divhealth.net }
        ###############################################
        #^# Make sure this matches the site matrix! #^#
        ###############################################
    with:
      docker_image: website-${{ matrix.site.dir }}
      site_host: ${{ matrix.site.dir }}
      ecr_registry: ${{ vars.AWS_ECR_REGISTRY }}
